---
- name: (Testing) generate root ca key
  hosts: localhost
  roles:
    - create_ca
    - issue_server_cert
  vars:
    ca_config_dir: /home/phess/tmp/test-ca-dir
    server_cert_name: aap24a-db.psi.ansible.cee.redhat.com
    
