---
ca_config_dir: "/etc/local-ca-by-ansible"

# Root CA
root_ca_dir: "{{ ca_config_dir }}/root-ca"
root_ca_key_file: "{{ root_ca_dir }}/root-ca.key"
root_ca_cert_file: "{{ root_ca_dir }}/root-ca.crt"
root_ca_csr_file: "{{ root_ca_dir }}/root-ca-csr.pem"
