---

### Based on https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html
- name: Do we have a key already?
  ansible.builtin.stat:
    path: "{{ server_key_file }}"
  register: key_file_stat

- name: "Stop now if key exists at {{ server_key_file }}"
  ansible.builtin.fail:
    msg: "Private key exists already at {{ server_key_file }}"
  when: key_file_stat.stat.exists and not ( replace_key_if_exists or use_existing_key )

- name: Set current private key status
  ansible.builtin.set_fact:
    key_file_exists: "{{ key_file_stat.stat.exists }}"
    private_key:
      file: "{{ server_key_file }}"
      exists: "{{ key_file_stat.stat.exists }}"
      stat: "{{ key_file_stat.stat }}"
      status: >
        {% if not key_file_stat.stat.exists %}
          created
        {% elif replace_key_if_exists %}
          replaced
        {% else %}
          exists
        {% endif %}

- name: Remove spaces and newlines from private_key.status
  ansible.builtin.set_fact:
    private_key:
      status: "{{ private_key.status.strip() }}"

- name: Show private key status
  ansible.builtin.debug:
    var: private_key.status

- name: "Ensure directory {{ server_cert_dir }} exists"
  ansible.builtin.file:
    path: "{{ server_cert_dir }}"
    state: directory

- name: Generate a new key
  no_log: false  # Set to True in production
  community.crypto.openssl_privatekey:
    # Always careful
    backup: yes
    force: "{{ replace_key_if_exists | default(False) }}"
    # Encrypt?
    passphrase: "{{ key_passphrase | default(None, False) }}"
    # Where?
    path: "{{ server_key_file }}"
    # Allow deep tweaking; values below are the defaults and can be removed.
    curve: "{{ key_curve | default('secp256r1') }}"
    format: "{{ key_format | default('auto_ignore') }}"
    # Key generation parameters
    size: "{{ key_size | default(4096) }}"
    type: "{{ key_type | default('RSA') }}"
    # Docs say this "must be auto".
    cipher: auto
  when: private_key.status != "exists"
    
- name: Private key permissions and ownership
  ansible.builtin.file:
    path: "{{ server_key_file }}"
    mode: 'g=-,o=-'
    
- name: Report
  ansible.builtin.debug:
    msg: "Private key {{ private_key.status }} at {{ server_key_file }}"
